### PR TITLE
Hide wind direction textual value

### PR DESCRIPTION
**Pull request by ilyapoz**
People seem to get confused about this wind direction textual value and navigational/meteorological distinction.

Maybe we should remove it alltogether? What do you think, @hr0nix?

### CODE REVIEW

**Comment by hr0nix** [comment]
I think it's useful to be able to see the exact value: people are not very good at judging angles precisely. We can put a [?] link near it, leading to the wikipedia article on wind direction :)

**Comment by ilyapoz** [comment]
:laughing: 
We can. But can you answer a qustion: yes, people are bad at it, but do they need to know the exact value in degrees?

**Comment by ilyapoz** [comment]
Maybe show it in a tooltip or something? Away from the attention.
It's all about simplifying the interface.

**Comment by hr0nix** [comment]
I think you're trying to simplify things too much. Skydivers are supposed to be capable of thinking, aren't they?

**Pull request closed without merging**
