### PR TITLE
UI Reorganization branch

### PR DESCRIPTION
**Pull request by ilyapoz**
For #58

### CODE REVIEW

**Comment by ilyapoz** [comment]
Check this pls @hr0nix

**Comment by hr0nix** [comment]
Organization is quite ok. But don't release it yet, the design requires certain improvements.

**Comment by ilyapoz** [comment]
This is a merge-to-master request.
And I need this for further development.

**Comment by hr0nix** [comment]
You can merge it yourself, use your judgement) I'm quite busy at work these days.

**Comment by ilyapoz** [comment]
I see, just asked for a bit of testing :)

**Pull request merged**
