### PR TITLE
Landing direction independent of the wind speed.

### PR DESCRIPTION
**Pull request by ilyapoz**
Replacing #13 with this pr.

### CODE REVIEW

**Comment by ilyapoz** [comment]
TODOs
1. ~~Add landing direction visual indication (the arrow)~~
2. ~~Need to add a setting to set landing direction into the wind automatically.~~
3. Come up with something for high winds as usual (currently it falls back to into-the-wind approach).

**Comment by ilyapoz** [comment]
Wow, this is unbelievable stuff :)
But you have to appreciate the crosswind landings.
Hint: set landing direction nearly perpendicular to the wind direction. Then think :)

**Comment by hr0nix** [comment]
Cool stuff

**Comment by ilyapoz** [comment]
I think this is mergeable now, the high winds issue should be a separate one anyway.
@hr0nix ? Do you like it this way? The "into the wind" checkbox, the arrow?

**Pull request merged**
