### PR TITLE
Custom LZ selection

### PR DESCRIPTION
**Pull request by ilyapoz**
We need to implement a custom LZ selector.

Google Maps API provides finder controls, use them.

### CODE REVIEW

**Comment by hr0nix** [comment]
An interface idea - https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete?hl=ru

**Comment by ilyapoz** [comment]
:+1:

**Comment by hr0nix** [comment]
@ilyapoz, check it out

**Comment by ilyapoz** [comment]
Wow this is rad :+1:

**Comment by ilyapoz** [comment]
Now we need to implement custom DZ persistence.
There is a bug anyway: be careful with refreshing the page with Custom DZ :tongue:

**Comment by ilyapoz** [comment]
Call `wipeCookies()` from development console if you were too curious.

**Comment by ilyapoz** [comment]
pushit :+1:

**Pull request merged**
